# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
collections:
  my_collection:
    output: true
    permalink: /:path/:name

# Setup
title:            FI Stoff
tagline:          'Stoffsammlung'
description:      'Stoffsammlung f√ºr Fachinformatiker in der Ausbildung'
url:              https://semoxea.github.io/
baseurl:          ""
github_username:  jekyll

paginate:         5

# Custom vars
version:          2.1.0

# Build settings
plugins:
  - jekyll-feed
